# -*- coding: utf-8 -*-
"""Practico01

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QNHnatD5xLLZcMnXrLZt-Kec58dWAVSn
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

np.random.seed(12)
estaturas = np.random.uniform(1.6, 2.0, 100)
pesos = []

for est in estaturas:
    min = 19.5 * (est**2)
    max = 23 * (est**2)
    peso = np.random.uniform(min, max)
    pesos.append(peso)

data = pd.DataFrame({
    'Estatura (m)': estaturas,
    'Peso (kg)': pesos
})

x = data['Estatura (m)']
y = data['Peso (kg)']
m = np.sum((x - np.mean(x)) * (y - np.mean(y))) / np.sum((x - np.mean(x)) ** 2)
b = np.mean(y) - m * np.mean(x)

y_line = m * x + b

plt.scatter(data['Estatura (m)'], data['Peso (kg)'], color='blue', label='Datos')
plt.plot(x, y_line, color='red', label='Línea ajustada')
plt.title('Estatura vs Peso con Línea Ajustada')
plt.xlabel('Estatura (m)')
plt.ylabel('Peso (kg)')
plt.legend()
plt.show()